
# For config examples see: https://github.com/resque/resque-scheduler#static-schedules

DeleteOldEmptyAdsJob:
  cron: "15 * * * *"
  queue: low
  description: "This job deletes all ads which are empty (and older then 6 hours)"

UserFeedbackScoreRefreshAllJob:
  cron:  "0 1 * * *"
  queue: low
  description: "Refresh feedback_score for all users"

BookingAutoAdjustStatusJob:
  cron:  "30 0 * * *"
  queue: low
  description: "Adjust status of bookings, for any bookings which could in in wrong status"

SitemapGeneratorJob:
  cron:  "30 3 * * *"
  queue: low
  description: "Generate sitemap.xml and ping search engines"

UnavailabilitiesCleanupJob:
  cron:  "0 1 * * *"
  queue: low
  description: "Delete unavailability entries that are in the past"

#queue_documents_for_indexing:
#  cron: "0 0 * * *"
#  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
#  # every: 1h
#  # By default the job name (hash key) will be taken as worker class name.
#  # If you want to have a different job name and class name, provide the 'class' option
#  class: "QueueDocuments"
#  queue: high
#  args:
#  description: "This job queues all content for indexing in solr"
#
#clear_leaderboards_contributors:
#  cron: "30 6 * * 1"
#  class: "ClearLeaderboards"
#  queue: low
#  args: contributors
#  description: "This job resets the weekly leaderboard for contributions"