require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UserPaymentCardsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # UserPaymentCard. As you add validations to UserPaymentCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserPaymentCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    xit "assigns all user_payment_cards as @user_payment_cards" do
      user_payment_card = UserPaymentCard.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:user_payment_cards)).to eq([user_payment_card])
    end
  end

  describe "GET #show" do
    xit "assigns the requested user_payment_card as @user_payment_card" do
      user_payment_card = UserPaymentCard.create! valid_attributes
      get :show, {:id => user_payment_card.to_param}, valid_session
      expect(assigns(:user_payment_card)).to eq(user_payment_card)
    end
  end

  describe "GET #new" do
    xit "assigns a new user_payment_card as @user_payment_card" do
      get :new, {}, valid_session
      expect(assigns(:user_payment_card)).to be_a_new(UserPaymentCard)
    end
  end

  describe "GET #edit" do
    it "assigns the requested user_payment_card as @user_payment_card" do
      user_payment_card = UserPaymentCard.create! valid_attributes
      get :edit, {:id => user_payment_card.to_param}, valid_session
      expect(assigns(:user_payment_card)).to eq(user_payment_card)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      xit "creates a new UserPaymentCard" do
        expect {
          post :create, {:user_payment_card => valid_attributes}, valid_session
        }.to change(UserPaymentCard, :count).by(1)
      end

      xit "assigns a newly created user_payment_card as @user_payment_card" do
        post :create, {:user_payment_card => valid_attributes}, valid_session
        expect(assigns(:user_payment_card)).to be_a(UserPaymentCard)
        expect(assigns(:user_payment_card)).to be_persisted
      end

      xit "redirects to the created user_payment_card" do
        post :create, {:user_payment_card => valid_attributes}, valid_session
        expect(response).to redirect_to(UserPaymentCard.last)
      end
    end

    context "with invalid params" do
      xit "assigns a newly created but unsaved user_payment_card as @user_payment_card" do
        post :create, {:user_payment_card => invalid_attributes}, valid_session
        expect(assigns(:user_payment_card)).to be_a_new(UserPaymentCard)
      end

      xit "re-renders the 'new' template" do
        post :create, {:user_payment_card => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      xit "updates the requested user_payment_card" do
        user_payment_card = UserPaymentCard.create! valid_attributes
        put :update, {:id => user_payment_card.to_param, :user_payment_card => new_attributes}, valid_session
        user_payment_card.reload
        skip("Add assertions for updated state")
      end

      xit "assigns the requested user_payment_card as @user_payment_card" do
        user_payment_card = UserPaymentCard.create! valid_attributes
        put :update, {:id => user_payment_card.to_param, :user_payment_card => valid_attributes}, valid_session
        expect(assigns(:user_payment_card)).to eq(user_payment_card)
      end

      xit "redirects to the user_payment_card" do
        user_payment_card = UserPaymentCard.create! valid_attributes
        put :update, {:id => user_payment_card.to_param, :user_payment_card => valid_attributes}, valid_session
        expect(response).to redirect_to(user_payment_card)
      end
    end

    context "with invalid params" do
      xit "assigns the user_payment_card as @user_payment_card" do
        user_payment_card = UserPaymentCard.create! valid_attributes
        put :update, {:id => user_payment_card.to_param, :user_payment_card => invalid_attributes}, valid_session
        expect(assigns(:user_payment_card)).to eq(user_payment_card)
      end

      xit "re-renders the 'edit' template" do
        user_payment_card = UserPaymentCard.create! valid_attributes
        put :update, {:id => user_payment_card.to_param, :user_payment_card => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    xit "destroys the requested user_payment_card" do
      user_payment_card = UserPaymentCard.create! valid_attributes
      expect {
        delete :destroy, {:id => user_payment_card.to_param}, valid_session
      }.to change(UserPaymentCard, :count).by(-1)
    end

    xit "redirects to the user_payment_cards list" do
      user_payment_card = UserPaymentCard.create! valid_attributes
      delete :destroy, {:id => user_payment_card.to_param}, valid_session
      expect(response).to redirect_to(user_payment_cards_url)
    end
  end

end
